# Generated by Django 2.2.5 on 2020-03-03 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5a76c93-e229-4cf7-93a0-debb5806b4c3'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9e87a7ac-0413-4593-b8b8-7e9b2d1413da'), editable=False, primary_key=True, serialize=False),
        ),
    ]
