# Generated by Django 2.2.5 on 2020-03-03 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_auto_20200303_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d75c9361-a4bb-4ed5-86d0-c40949822a93'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='status',
            field=models.CharField(default='ENABLED', max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1304449d-131e-4d09-b956-53c77eabbe1c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
