# Generated by Django 2.2.5 on 2020-03-05 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200303_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privilege',
            name='id',
            field=models.UUIDField(default=uuid.UUID('335e9cfc-633f-4019-af88-739cc075967d'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='id',
            field=models.UUIDField(default=uuid.UUID('eee2df66-3548-4aac-a4f7-2474f3ce2c33'), editable=False, primary_key=True, serialize=False),
        ),
    ]
