# Generated by Django 2.2.5 on 2020-03-02 15:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('name_of_asset', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('credit_card_number', models.CharField(max_length=100)),
                ('credit_card_exp_date', models.CharField(max_length=20)),
                ('credit_card_cvc', models.CharField(max_length=200)),
                ('credit_card_issuer', models.CharField(max_length=256)),
            ],
            bases=('assets.asset',),
        ),
    ]
