# Generated by Django 3.0.3 on 2020-03-07 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveDirectoryAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('name_of_asset', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('username', models.CharField(blank=True, max_length=500)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('groups', models.CharField(blank=True, max_length=50)),
                ('roles', models.CharField(blank=True, max_length=50)),
                ('block_sign_in', models.CharField(blank=True, max_length=50)),
                ('usage_location', models.CharField(blank=True, max_length=50)),
                ('job_title', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('ad_account_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCardAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_asset', models.CharField(max_length=50)),
                ('name_of_asset', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('credit_card_number', models.CharField(max_length=100)),
                ('credit_card_exp_date', models.CharField(max_length=20)),
                ('credit_card_cvc', models.CharField(max_length=200)),
                ('credit_card_issuer', models.CharField(max_length=256)),
            ],
        ),
    ]
