# Generated by Django 2.2.5 on 2020-03-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_activedirectoryasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='activedirectoryasset',
            name='block_sign_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='groups',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='job_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='roles',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='usage_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='activedirectoryasset',
            name='username',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
